'use strict';
const labels=['簡報設定','講師與內容','品牌素材','逐頁預覽','檢核與匯出'];
const fresh=()=>({schemaVersion:2,step:0,index:0,title:'',audience:'扶輪社友',year:'',pages:18,speaker:'',role:'',bio:'',source:'',chatgptResult:'',photoSource:null,portrait:null,photoName:'',portraitStyle:'arch',zoom:1,focusX:50,focusY:40,reviewed:false,slides:[],research:'',generatedAt:null});
const storageMode=location.hostname.endsWith('.github.io')||location.protocol==='file:'||new URLSearchParams(location.search).get('storage')==='browser'?'browser':'sites';
let state=fresh(),draftId=null,draftETag=null,dirty=false,revision=0,officialLogo=null,status={storageReady:storageMode==='browser',aiMode:'chatgpt-account'},session={signedIn:storageMode==='browser',email:'',name:''},portraitTimer=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const layoutNames={text:'重點文字',image:'圖文並列',comparison:'比較表',flow:'流程圖'};
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
const safeImage=s=>typeof s==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s)?s:null;
function message(text){$('#notice').textContent=text;}
function touch(){dirty=true;revision++;state.reviewed=false;$('#saveStatus').textContent='有尚未儲存的修改';}
function busy(title,text=''){const overlay=$('#busyOverlay');overlay.hidden=!title;$('#busyTitle').textContent=title||'';$('#busyText').textContent=text;}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Studio-Request':'1',...(options.headers||{})}});let result;try{result=await response.json();}catch{throw Error('網站連線未完成，請重新登入或稍後重試。');}if(!response.ok)throw Error(result.error||'操作未完成。');return result;}
function draftDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('rotary-slide-studio',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('drafts'))db.createObjectStore('drafts',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('瀏覽器草稿儲存空間無法開啟。'));});}
async function browserDrafts(mode,id,value){const db=await draftDB();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode==='list'||mode==='get'?'readonly':'readwrite'),store=tx.objectStore('drafts'),request=mode==='list'?store.getAll():mode==='get'?store.get(id):store.put(value);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('草稿儲存未完成。'));tx.oncomplete=()=>db.close();});}
function field(key,label,type='text',placeholder=''){return `<label class="field">${label}${type==='textarea'?`<textarea data-key="${key}" placeholder="${esc(placeholder)}">${esc(state[key])}</textarea>`:`<input data-key="${key}" type="${type}" value="${esc(state[key])}" placeholder="${esc(placeholder)}">`}</label>`;}
function syncFixed(){if(!state.slides.length)return;state.slides[0]={kind:'cover',layout:'cover',title:state.title,body:`${state.speaker}｜${state.role}\n${state.audience}${state.year?'　·　'+state.year:''}`,sources:[]};state.slides[1]={kind:'speaker',layout:'speaker',title:`講師介紹｜${state.speaker}`,body:`${state.role}\n${state.bio}`,sources:[]};state.slides[2]={kind:'agenda',layout:'agenda',title:'今日分享目錄',body:state.slides.slice(3).map((s,i)=>`${String(i+1).padStart(2,'0')}　${s.title}`).join('\n'),sources:[]};}
function navigate(step){state.step=step;render();}
function render(){syncFixed();state.index=Math.max(0,Math.min(state.index,state.slides.length-1));$('#steps').innerHTML=labels.map((l,i)=>`<button data-step="${i}" class="${i===state.step?'active':''}" aria-current="${i===state.step?'step':'false'}"><b>${i+1}</b>${l}</button>`).join('');$('#stepNo').textContent=`STEP 0${state.step+1} / 05`;$('#stepTitle').textContent=labels[state.step];$('#pageCount').textContent=`${state.pages} 頁 · 前 3 頁固定`;$('#back').disabled=state.step===0;$('#next').hidden=state.step===4;message('');const panel=$('#panel');
if(state.step===0)panel.innerHTML=`<div class="card"><h2>設定這次分享的主題</h2><p class="muted">確定聽眾與篇幅，選擇使用 ChatGPT 或貼上資料編排。</p>${field('title','簡報主題','text','例如：扶輪服務專案的規劃與實踐')}<div class="grid">${field('audience','分享對象')}<label class="field">簡報頁數<select data-key="pages">${[15,16,17,18,19,20].map(n=>`<option ${state.pages===n?'selected':''}>${n}</option>`).join('')}</select></label>${field('year','扶輪年度（選填）','text','例如：2026–2027')}</div></div><div class="card"><h2>固定的開場，清楚的脈絡</h2><div class="grid"><p><strong>01　封面</strong><br><span class="help">主題、講師與地區</span></p><p><strong>02　講師介紹</strong><br><span class="help">姓名、經歷與講師合成圖</span></p><p><strong>03　目錄</strong><br><span class="help">依內容頁標題自動更新</span></p><p><strong>04 起　主題內容</strong><br><span class="help">文字、圖文、比較表、流程圖</span></p></div></div>`;
if(state.step===1)panel.innerHTML=`<div class="card"><h2>講師介紹</h2><div class="grid">${field('speaker','講師姓名')}${field('role','職稱／所屬扶輪社')}</div>${field('bio','簡介與相關經歷','textarea','建議 3 至 5 項，合計不超過 180 字。')}<div class="photo-workspace"><div><h3>講師照片合成</h3><p class="help">上傳照片後，合成適合講師頁的藍金色人物圖。請選擇已取得使用同意的照片。</p><label class="field">上傳講師照片<input id="photoFile" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="field">合成樣式<select id="portraitStyle"><option value="arch" ${state.portraitStyle==='arch'?'selected':''}>典雅拱形</option><option value="card" ${state.portraitStyle==='card'?'selected':''}>專業方框</option><option value="circle" ${state.portraitStyle==='circle'?'selected':''}>圓形聚焦</option></select></label>${state.photoSource?`<label class="field">照片大小<input id="zoom" type="range" min="1" max="2" step="0.05" value="${state.zoom}"></label><label class="field">左右位置<input id="focusX" type="range" min="0" max="100" value="${state.focusX}"></label><label class="field">上下位置<input id="focusY" type="range" min="0" max="100" value="${state.focusY}"></label><button id="downloadPortrait" class="secondary">下載講師合成圖</button>`:''}</div><div id="portraitPreview">${state.portrait?`<img src="${safeImage(state.portrait)||''}" alt="講師合成圖預覽">`:'<div class="photo-placeholder">上傳照片<br><span>自動合成並放入第 2 頁</span></div>'}</div></div></div><div class="card ai-card"><div class="section-head"><h2>使用自己的 ChatGPT 產生內容</h2><span class="tag ok">不需要提供 API Key</span></div><p>網站會依照目前的主題、對象、年度與頁數準備完整製作指令。請在自己的 ChatGPT 帳號中搜尋官方來源並產生 ${state.pages-3} 頁內容，再將結果貼回匯入。</p><p class="help">講師照片與私人講稿不會傳送。ChatGPT 可用功能與用量依照使用者自己的方案決定；匯入後仍需逐頁核對來源、年度與地區適用性。</p><div class="actions"><button id="copyChatGPTPrompt">複製 ChatGPT 製作指令</button><a class="button-link secondary" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">開啟 ChatGPT</a></div><details><summary>貼回 ChatGPT 產生的結果</summary><label class="field">ChatGPT JSON 結果<textarea id="chatgptResult" rows="8" placeholder="將 ChatGPT 回傳的 JSON 貼在這裡">${esc(state.chatgptResult||'')}</textarea></label><button id="importChatGPT">匯入並建立 ${state.pages} 頁簡報</button></details></div><div class="card"><h2>或貼上自己的講稿</h2><p class="help">空白行分段，每段第一行為標題。保留原文編排；不足的頁面留待補充，超出容量會提示。</p>${field('source','講稿／主題資料','textarea','每段第一行填寫標題\n下一行開始填寫內容\n\n另一個主題\n主題內容')}<button id="compose">依資料編排 ${state.pages} 頁</button></div>`;
if(state.step===2)panel.innerHTML=`<div class="card"><h2>已套用您的官方地區 Logo</h2><div class="official-logo"><img src="assets/district-logo.png" alt="Rotary District 3510 官方地區 Logo"></div><p class="help">素材：地區Logo.png。所有簡報固定採用這份原圖，保留完整比例與顏色；外圍另留安全空間。講師合成圖不包含重畫的扶輪標誌。</p></div><div class="card"><h2>品牌使用檢核</h2><ul class="rules"><li>文字標誌與齒輪保持完整，不拆解、不裁切、不改色。</li><li>標誌外圍預留至少「R」字高度的安全空間。</li><li>沿用您提供的地區名稱與標誌排列，不重新組字。</li><li>採藍、金、白色系，簡報字型設定為思源黑體 TW。</li></ul><p class="help">依據您提供的《扶輪標誌使用規範》，2019 年 12 月版。工具提供版面限制與人工檢核，並非國際扶輪官方認證。</p></div>`;
if(state.step===3)panel.innerHTML=state.slides.length?previewPanel():'<div class="card"><h2>先建立簡報內容</h2><p>請在「講師與內容」從 ChatGPT 匯入結果，或貼上講稿編排。</p></div>';
if(state.step===4){const checks=validate();panel.innerHTML=`<div class="card"><h2>輸出前，完成最後確認</h2>${checks.map(c=>`<div class="status"><span>${esc(c[0])}</span><b class="${c[1]?'ok':'fail'}">${c[1]?'通過':'待完成'}</b></div>`).join('')}<label class="check"><input id="reviewed" type="checkbox" ${state.reviewed?'checked':''}>我已逐頁核對內容、年度、引用與圖片使用同意，並確認 Logo 顯示完整、清晰及留白。</label><button id="export" ${checks.every(c=>c[1])&&state.reviewed?'':'disabled'}>下載可編輯 PPTX</button><p class="help" style="margin-top:16px">文字、比較表與流程圖可在 PowerPoint 編輯；講師合成圖及照片以圖片置入。引用連結會出現在頁面註腳與備註。完成修改後請儲存草稿。</p></div><div class="callout">此預覽為版面示意。匯出後請在 PowerPoint 確認字型與換行，後續修改仍須遵守品牌規範。</div>`;}
bind();}
function tableRows(text){return String(text||'').split('\n').filter(x=>x.trim()).map(line=>line.split('|').map(x=>x.trim()));}
function flowSteps(text){return String(text||'').split('\n').map(x=>x.trim()).filter(Boolean);}
function citationsHTML(s){return (s.sources||[]).map((r,i)=>safeURL(r.url)?`<a href="${esc(safeURL(r.url))}" target="_blank" rel="noopener noreferrer">[${i+1}] ${esc(r.title)}</a>`:'').join('　');}
function slideMarkup(s,index){let inside='';const layout=s.layout||'text';if(s.kind==='speaker'&&state.portrait)inside=`<img class="speaker-art" src="${safeImage(state.portrait)||''}" alt="講師合成圖"><div class="body speaker-body">${esc(s.body)}</div>`;
else if(layout==='image')inside=`<div class="body image-body">${esc(s.body)}</div>${s.image?`<img class="content-photo" src="${safeImage(s.image)||''}" alt="${esc(s.imageCaption||'內容圖片')}">`:'<div class="content-photo image-placeholder">請上傳本頁圖片</div>'}<div class="photo-caption">${esc(s.imageCaption||'')}</div>`;
else if(layout==='comparison'){const rows=tableRows(s.table);inside=`<div class="body layout-intro">${esc(s.body)}</div><table class="compare-table">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${esc(c)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table>`;}
else if(layout==='flow'){const steps=flowSteps(s.steps);inside=`<div class="body layout-intro">${esc(s.body)}</div><div class="flow-nodes">${steps.map((v,i)=>`<div class="flow-node"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(v)}</span></div>`).join('')}</div>`;}
else inside=`<div class="body">${esc(s.body)}</div>`;
return `<div class="slide ${s.kind} ${layout}" aria-label="第 ${index+1} 頁預覽"><div class="strip"></div><div class="kicker">國際扶輪 3510 地區</div><div class="logo-space"><img src="assets/district-logo.png" alt="官方地區標誌"></div><h2>${esc(s.title)}</h2>${inside}<div class="slide-citations">${citationsHTML(s)}</div><div class="bottom">${esc(state.speaker)}　／　${String(index+1).padStart(2,'0')}</div></div>`;}
function previewPanel(){const s=state.slides[state.index];return `<div class="preview-shell"><div class="thumbs">${state.slides.map((s,i)=>`<button data-slide="${i}" class="${i===state.index?'selected':''}">${String(i+1).padStart(2,'0')}<br>${esc(s.title)}</button>`).join('')}</div><div><div id="liveSlide">${slideMarkup(s,state.index)}</div><div class="editor card">${state.index<3?'<p class="help">前三頁固定，請回到前面步驟修改主題與講師資料。</p>':`<label class="field">頁面標題<input id="slideTitle" maxlength="40" value="${esc(s.title)}"></label><label class="field">版型<select id="slideLayout">${Object.entries(layoutNames).map(([key,name])=>`<option value="${key}" ${key===(s.layout||'text')?'selected':''}>${name}</option>`).join('')}</select></label><label class="field">${['flow','comparison'].includes(s.layout)?'重點說明（建議 60 字內）':'頁面內容（建議 180 字內）'}<textarea id="slideBody" rows="4">${esc(s.body)}</textarea></label>${s.layout==='image'?`<label class="field">本頁圖片<input id="contentPhoto" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="field">圖片說明<input id="imageCaption" maxlength="60" value="${esc(s.imageCaption||'')}"></label>`:''}${s.layout==='comparison'?`<label class="field">比較表內容<textarea id="tableText" rows="5" placeholder="項目 | 方案 A | 方案 B\n比較項目 | 說明 | 說明">${esc(s.table||'')}</textarea></label><p class="help">每行一列，以 | 分欄；第 1 列為表頭。限 2 至 4 欄、2 至 5 列，每格最多 28 字。</p>`:''}${s.layout==='flow'?`<label class="field">流程步驟<textarea id="stepsText" rows="5" placeholder="需求訪談\n規劃方案\n執行服務\n成果追蹤">${esc(s.steps||'')}</textarea></label><p class="help">每行一個步驟，限 3 至 5 步，每步最多 24 字。</p>`:''}<label class="field">來源（每行：標題 | 網址）<textarea id="sourceText" rows="3" placeholder="來源標題 | https://...">${esc(s.sourceText||'')}</textarea></label><p class="help">${['ai','chatgpt'].includes(s.origin)?'ChatGPT 產生內容，來源已取自實際搜尋引用；請逐頁核對是否支持敘述。':'可填入您採用的資料來源。'} 所有修改會即時更新預覽。</p>`}</div>${s.sources?.length?`<div class="card sources"><h3>本頁資料來源</h3>${s.sources.map((r,i)=>`<p>${safeURL(r.url)?`<a href="${esc(safeURL(r.url))}" target="_blank" rel="noopener noreferrer">[${i+1}] ${esc(r.title)}</a>`:''}${r.fetchedAt?`<small>查詢日期：${esc(new Date(r.fetchedAt).toLocaleDateString('zh-TW'))}</small>`:''}</p>`).join('')}${s.note?`<p class="help">${esc(s.note)}</p>`:''}</div>`:''}</div></div>`;}
function bind(){document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>navigate(+b.dataset.step));document.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>{state[el.dataset.key]=el.dataset.key==='pages'?+el.value:el.value;touch();if(el.dataset.key==='pages')$('#pageCount').textContent=`${state.pages} 頁 · 前 3 頁固定`;});if($('#compose'))$('#compose').onclick=compose;if($('#copyChatGPTPrompt'))$('#copyChatGPTPrompt').onclick=copyChatGPTPrompt;if($('#chatgptResult'))$('#chatgptResult').oninput=e=>{state.chatgptResult=e.target.value;touch();};if($('#importChatGPT'))$('#importChatGPT').onclick=importChatGPT;if($('#photoFile'))$('#photoFile').onchange=uploadPortrait;
if($('#portraitStyle'))$('#portraitStyle').onchange=()=>{state.portraitStyle=$('#portraitStyle').value;touch();updatePortrait().catch(e=>message(e.message));};for(const key of ['zoom','focusX','focusY'])if($('#'+key))$('#'+key).oninput=e=>{state[key]=+e.target.value;touch();clearTimeout(portraitTimer);portraitTimer=setTimeout(()=>updatePortrait().catch(e=>message(e.message)),100);};if($('#downloadPortrait'))$('#downloadPortrait').onclick=()=>downloadData(state.portrait,`${state.speaker||'講師'}-合成圖.png`);
document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.slide;render();});const s=state.slides[state.index];if(s&&state.index>=3){for(const [id,key] of [['slideTitle','title'],['slideBody','body'],['tableText','table'],['stepsText','steps'],['imageCaption','imageCaption'],['sourceText','sourceText']])if($('#'+id))$('#'+id).oninput=e=>{s[key]=e.target.value;if(key==='sourceText')s.sources=parseSources(e.target.value);touch();syncFixed();$('#liveSlide').innerHTML=slideMarkup(s,state.index);};if($('#slideLayout'))$('#slideLayout').onchange=e=>{s.layout=e.target.value;touch();render();};if($('#contentPhoto'))$('#contentPhoto').onchange=async e=>{try{s.image=await readPhoto(e.target.files[0]);touch();render();}catch(error){message(error.message);}};}
if($('#reviewed'))$('#reviewed').onchange=e=>{state.reviewed=e.target.checked;dirty=true;revision++;$('#saveStatus').textContent='有尚未儲存的修改';$('#export').disabled=!(state.reviewed&&validate().every(c=>c[1]));};if($('#export'))$('#export').onclick=exportDeck;}
function parseSources(text){return String(text||'').split('\n').filter(x=>x.trim()).map(line=>{const [title,...rest]=line.split('|');const url=safeURL(rest.join('|').trim());return {title:title.trim(),url};}).filter(x=>x.title&&x.url);}
function compose(){if(!state.title.trim()||!state.source.trim()){message('請先填寫主題與內容資料。');return;}const out=[];for(const block of state.source.trim().split(/\n\s*\n/)){const lines=block.split('\n');const title=lines.length>1?lines.shift().trim():'主題內容';const body=lines.join('\n');const chunks=Array.from(body).reduce((acc,c)=>{if(!acc.length||Array.from(acc.at(-1)).length>=180)acc.push('');acc[acc.length-1]+=c;return acc;},[]);(chunks.length?chunks:['']).forEach((b,i)=>out.push({kind:'content',layout:'text',title:title+(i?'（續）':''),body:b,table:'',steps:'',sourceText:'',sources:[],image:null,imageCaption:''}));}if(out.length>state.pages-3){message(`資料需要 ${out.length+3} 頁，請精簡資料或增加頁數（上限 20）。原稿已保留。`);return;}if(state.slides.length&&!confirm('重新編排會取代目前投影片，是否繼續？'))return;while(out.length<state.pages-3)out.push({kind:'content',layout:'text',title:`待補充主題 ${out.length+1}`,body:'',sources:[]});state.slides=[{},{},{},...out];state.index=0;touch();navigate(3);}
function chatGPTPrompt(){if(!state.title.trim())throw Error('請先在「簡報設定」填寫主題。');const count=state.pages-3;return `請為「國際扶輪 3510 地區」講師製作一份繁體中文簡報內容。\n\n主題：${state.title}\n對象：${state.audience}\n扶輪年度：${state.year||'未指定，涉及年度的資料請標示待確認'}\n總頁數：${state.pages} 頁；網站會自動建立封面、講師介紹與目錄，請只產生 ${count} 張正式內容頁。\n\n請先使用網路搜尋，優先採用 https://www.rotary.org 與 https://rid3510.org 的官方資料。每項事實與數字都要有可直接開啟的來源網址。不可把國際扶輪的一般制度說成 3510 地區的特定成果；資料不足時請清楚標示「待確認」，不可推測。\n\n頁面可使用 text、comparison、flow 三種版型。comparison 的 table 為 2 至 5 行、2 至 4 欄，每行用 | 分隔；flow 的 steps 為 3 至 5 步，每行一步。每頁標題最多 40 字，body 最多 220 字且最多 8 行。\n\n最後只輸出一個有效 JSON 物件，不要加 Markdown 程式碼框、前言或結語，格式如下：\n{"slides":[{"title":"頁面標題","body":"重點內容","layout":"text","table":"","steps":"","sources":[{"title":"來源名稱","url":"https://www.rotary.org/..."}],"note":""}]}\n\nslides 必須剛好有 ${count} 筆。事實頁必須有 1 至 3 個真正支持該頁內容的來源；只有標題明確包含「討論」或「練習」的教學活動頁可以沒有來源。`;}
async function copyChatGPTPrompt(){try{await navigator.clipboard.writeText(chatGPTPrompt());message('製作指令已複製。請開啟 ChatGPT、貼上並送出，再把 JSON 結果貼回此頁。');}catch(error){message(error.message||'無法複製，請允許瀏覽器存取剪貼簿。');}}
function officialSourceURL(value){const url=safeURL(value);if(!url)return null;try{const host=new URL(url).hostname.toLowerCase();return host==='rotary.org'||host.endsWith('.rotary.org')||host==='rid3510.org'||host.endsWith('.rid3510.org')?url:null;}catch{return null;}}
function normalizeImportedSlides(data){if(!data||!Array.isArray(data.slides)||data.slides.length!==state.pages-3)throw Error(`內容頁必須剛好有 ${state.pages-3} 張。`);const fetchedAt=new Date().toISOString();return data.slides.map((raw,index)=>{const title=String(raw?.title||'').trim(),body=String(raw?.body||'').trim(),layout=['text','comparison','flow'].includes(raw?.layout)?raw.layout:'text',table=String(raw?.table||''),steps=String(raw?.steps||''),note=String(raw?.note||'');if(!title||title.length>40||!body||body.length>220||body.split('\n').length>8)throw Error(`第 ${index+4} 頁的標題或內容長度不符合規則。`);const sources=(Array.isArray(raw?.sources)?raw.sources:[]).map(item=>({title:String(item?.title||'官方資料').slice(0,160),url:officialSourceURL(item?.url),fetchedAt})).filter(item=>item.url).slice(0,3);if(!sources.length&&!/討論|練習/.test(title))throw Error(`第 ${index+4} 頁沒有可接受的扶輪官方來源。`);return {kind:'content',layout,title,body,table,steps,note,sources,origin:'chatgpt',image:null,imageCaption:'',sourceText:sources.map(x=>`${x.title} | ${x.url}`).join('\n')};});}
function parseChatGPTResult(text){const cleaned=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<=start)throw Error('找不到有效的 JSON 內容。');try{return JSON.parse(cleaned.slice(start,end+1));}catch{throw Error('JSON 格式不完整。請要求 ChatGPT 只輸出 JSON 後再貼回。');}}
function importChatGPT(){try{const slides=normalizeImportedSlides(parseChatGPTResult(state.chatgptResult));if(state.slides.length&&!confirm('匯入會取代目前投影片，是否繼續？'))return;state.slides=[{},{},{},...slides];state.generatedAt=new Date().toISOString();state.index=3;touch();navigate(3);message('ChatGPT 內容已匯入。請逐頁核對來源與敘述，再儲存草稿。');}catch(error){message(error.message);}}
function validate(){const content=state.slides.slice(3);const limits=s=>{if(s.title.length>40||s.body.length>220)return false;if(s.layout==='comparison'){const rows=tableRows(s.table);return s.body.length<=70&&rows.length>=2&&rows.length<=5&&rows[0].length>=2&&rows[0].length<=4&&rows.every(r=>r.length===rows[0].length&&r.every(c=>c.length>0&&c.length<=28));}if(s.layout==='flow'){const steps=flowSteps(s.steps);return s.body.length<=70&&steps.length>=3&&steps.length<=5&&steps.every(x=>x.length<=24);}return s.body.split('\n').length<=8;};return [['頁數為 15 至 20，且符合設定',state.slides.length===state.pages&&state.pages>=15&&state.pages<=20],['前三頁固定為封面、講師介紹、目錄',state.slides.slice(0,3).map(s=>s.kind).join(',')==='cover,speaker,agenda'],['講師姓名、職稱與簡介完整',!!state.speaker.trim()&&!!state.role.trim()&&!!state.bio.trim()&&state.bio.length<=180],['主題及每頁內容完整，沒有待補充內容',!!state.title.trim()&&state.title.length<=40&&content.length>0&&content.every(s=>s.title.trim()&&s.body.trim()&&!/待補充|待確認/.test(s.title+s.body))],['版型的文字、比較欄位與流程長度適合版面',content.length>0&&content.every(limits)],['圖文頁均有圖片，來源網址格式正確',content.every(s=>(s.layout!=='image'||!!safeImage(s.image))&&String(s.sourceText||'').split('\n').filter(x=>x.trim()).length===parseSources(s.sourceText||'').length)],['ChatGPT 事實頁保有來源引用',content.every(s=>!['ai','chatgpt'].includes(s.origin)||s.sources?.length||/討論|練習/.test(s.title))],['指定地區 Logo 已載入',!!officialLogo]];}
async function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('無法讀取圖片。'));image.src=src;});}
async function readPhoto(file){if(!file)throw Error('尚未選擇圖片。');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('請上傳 8 MB 以下的 PNG、JPG 或 WebP 照片。');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const img=await loadImage(src);if(img.width<150||img.height<150)throw Error('照片太小，請使用至少 150 × 150 像素的圖片。');const scale=Math.min(1,1600/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL(file.type==='image/png'?'image/png':'image/jpeg',.88);}
async function uploadPortrait(event){try{const file=event.target.files[0];if(!file)return;const data=await readPhoto(file);state.photoSource=data;state.photoName=file.name;state.zoom=1;state.focusX=50;state.focusY=40;touch();await updatePortrait();render();}catch(e){message(e.message);}}
let portraitVersion=0;
async function updatePortrait(){if(!state.photoSource)return;const version=++portraitVersion,photo=await loadImage(state.photoSource);if(version!==portraitVersion)return;const c=document.createElement('canvas');c.width=1000;c.height=1250;const ctx=c.getContext('2d');ctx.fillStyle='#0c3c7c';ctx.fillRect(0,0,1000,1250);ctx.fillStyle='#0050a2';ctx.beginPath();ctx.arc(970,60,600,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7a81b';ctx.fillRect(60,1120,210,12);const box=state.portraitStyle==='circle'?{x:90,y:185,w:820,h:820}:{x:95,y:95,w:810,h:1000};ctx.save();ctx.beginPath();if(state.portraitStyle==='circle')ctx.arc(500,595,410,0,Math.PI*2);else if(state.portraitStyle==='arch'){ctx.moveTo(95,1095);ctx.lineTo(95,500);ctx.bezierCurveTo(95,-40,905,-40,905,500);ctx.lineTo(905,1095);ctx.closePath();}else ctx.roundRect(box.x,box.y,box.w,box.h,24);ctx.clip();ctx.fillStyle='#edf2f8';ctx.fillRect(0,0,1000,1250);const scale=Math.max(box.w/photo.width,box.h/photo.height)*state.zoom,w=photo.width*scale,h=photo.height*scale;ctx.drawImage(photo,box.x-(w-box.w)*state.focusX/100,box.y-(h-box.h)*state.focusY/100,w,h);ctx.restore();ctx.fillStyle='white';ctx.font='24px sans-serif';ctx.fillText('DISTRICT 3510  /  SPEAKER',60,1190);state.portrait=c.toDataURL('image/png');const preview=$('#portraitPreview');if(preview)preview.innerHTML=`<img src="${state.portrait}" alt="講師合成圖預覽">`;}
function downloadData(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
async function saveDraft(copy=false){if(storageMode==='sites'&&!session.signedIn){location.href='/signin-with-chatgpt?return_to=%2F';return;}if($('#busyOverlay').hidden===false)return;clearTimeout(portraitTimer);if(state.photoSource)await updatePortrait();syncFixed();const snapshot=JSON.stringify(state),startRevision=revision;const id=copy?null:draftId;$('#saveDraft').disabled=true;$('#saveStatus').textContent='正在儲存…';try{let result;if(storageMode==='browser'){const updatedAt=new Date().toISOString(),localId=id||crypto.randomUUID();await browserDrafts('put',localId,{id:localId,updatedAt,title:state.title||'未命名簡報',speaker:state.speaker,pages:state.pages,data:JSON.parse(snapshot)});result={id:localId,etag:updatedAt,updatedAt};}else result=await api(id?`/api/drafts/${id}`:'/api/drafts',{method:id?'PUT':'POST',headers:id?{'If-Match':draftETag}:{},body:snapshot});draftId=result.id;draftETag=result.etag;if(revision===startRevision)dirty=false;$('#saveStatus').textContent=dirty?'已儲存，仍有較新的修改':`已儲存 ${new Date(result.updatedAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`;message(storageMode==='browser'?'草稿已儲存在這台裝置的瀏覽器。':'草稿已儲存，包含講師照片、版型與來源。');if($('#draftDialog').open)await listDrafts();}catch(e){$('#saveStatus').textContent='儲存未完成';message(e.message);if($('#draftDialog').open)$('#draftList').textContent=e.message;}finally{$('#saveDraft').disabled=storageMode==='sites'&&!session.signedIn;}}
async function listDrafts(){const list=$('#draftList');list.innerHTML='<p>正在讀取草稿…</p>';try{const result=storageMode==='browser'?{drafts:(await browserDrafts('list')).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}:await api('/api/drafts');list.innerHTML=result.drafts.length?result.drafts.map(d=>`<div class="draft-row"><div><strong>${esc(d.title)}</strong><p class="help">${esc(d.speaker||'尚未填寫講師')} · ${esc(d.pages)} 頁 · ${esc(new Date(d.updatedAt).toLocaleString('zh-TW'))}</p></div><button data-open="${esc(d.id)}">開啟</button></div>`).join(''):'<div class="card"><p>尚無草稿。填寫內容後，按右上角「儲存草稿」。</p></div>';if(result.truncated)list.insertAdjacentHTML('beforeend','<p class="help">僅顯示前 1,000 份草稿。</p>');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDraft(b.dataset.open));}catch(e){list.textContent=e.message;}}
function normalizeDraft(data){if(!data||data.schemaVersion!==2||!Array.isArray(data.slides)||data.slides.length>20||!Number.isInteger(data.pages)||data.pages<15||data.pages>20)throw Error('草稿版本或格式不正確。');const next={...fresh(),...data};for(const key of ['title','audience','year','speaker','role','bio','source','chatgptResult'])next[key]=String(next[key]||'');next.photoSource=safeImage(next.photoSource);next.portrait=safeImage(next.portrait);next.zoom=Math.min(2,Math.max(1,+next.zoom||1));next.focusX=Math.min(100,Math.max(0,+next.focusX||0));next.focusY=Math.min(100,Math.max(0,+next.focusY||0));next.portraitStyle=['arch','card','circle'].includes(next.portraitStyle)?next.portraitStyle:'arch';next.step=0;next.index=0;next.slides=next.slides.map((s,i)=>({...s,title:String(s.title||''),body:String(s.body||''),layout:i<3?['cover','speaker','agenda'][i]:Object.keys(layoutNames).includes(s.layout)?s.layout:'text',image:safeImage(s.image),sources:(Array.isArray(s.sources)?s.sources:[]).filter(x=>x&&safeURL(x.url)).map(x=>({...x,title:String(x.title||''),url:safeURL(x.url)}))}));return next;}
async function openDraft(id){if(dirty&&!confirm('目前有尚未儲存的修改。開啟其他草稿將放棄這些修改，是否繼續？'))return;try{const result=storageMode==='browser'?await browserDrafts('get',id):await api(`/api/drafts/${id}`);if(!result)throw Error('找不到這份草稿。');const next=normalizeDraft(result.data);state=next;draftId=result.id;draftETag=result.etag||result.updatedAt;dirty=false;revision++;$('#saveStatus').textContent=`已開啟：${state.title||'未命名簡報'}`;$('#draftDialog').close();render();message('草稿已重新開啟。');}catch(e){$('#draftList').textContent=e.message;}}
async function exportDeck(){syncFixed();if(!state.reviewed||!validate().every(c=>c[1]))return;$('#export').disabled=true;message('正在製作 PowerPoint…');try{await buildPptx({...state,logo:officialLogo,logoRatio:3695/1401},PptxGenJS).writeFile({fileName:state.title.replace(/[\\/:*?"<>|]/g,'_')+'.pptx'});message('PPTX 已產生，請查看瀏覽器下載項目。');}catch(e){message('匯出未完成：'+e.message);}finally{if($('#export'))$('#export').disabled=false;}}
function renderAccount(){const label=$('#accountStatus'),action=$('#accountAction');if(storageMode==='browser'){label.textContent='草稿儲存在此瀏覽器';action.hidden=true;action.style.display='none';$('#draftStorageHelp').textContent='草稿只儲存在這台裝置的瀏覽器，可重新開啟繼續編輯。';}else{label.textContent=session.signedIn?`已登入：${session.name||session.email||'ChatGPT 使用者'}`:'尚未登入；仍可在本機編輯與匯出';action.hidden=false;action.style.display='';action.textContent=session.signedIn?'登出':'使用 ChatGPT 登入';action.href=session.signedIn?'/signout-with-chatgpt?return_to=%2F':'/signin-with-chatgpt?return_to=%2F';}$('#saveDraft').disabled=storageMode==='sites'&&!session.signedIn;$('#openDrafts').disabled=storageMode==='sites'&&!session.signedIn;}
$('#back').onclick=()=>navigate(state.step-1);$('#next').onclick=()=>navigate(state.step+1);$('#saveDraft').onclick=()=>saveDraft();$('#openDrafts').onclick=()=>{if(storageMode==='sites'&&!session.signedIn){location.href='/signin-with-chatgpt?return_to=%2F';return;}$('#draftDialog').showModal();listDrafts();};$('#closeDrafts').onclick=()=>$('#draftDialog').close();$('#saveCopy').onclick=()=>saveDraft(true);$('#newDraft').onclick=()=>{if(dirty&&!confirm('放棄尚未儲存的修改，建立新簡報？'))return;state=fresh();draftId=null;draftETag=null;dirty=false;revision++;$('#saveStatus').textContent='新簡報';$('#draftDialog').close();render();};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
render();fetch('assets/district-logo.png').then(r=>{if(!r.ok)throw Error('Logo 載入失敗');return r.blob();}).then(blob=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(blob);})).then(data=>{officialLogo=data;if(state.step===4)render();}).catch(()=>message('官方 Logo 未能載入，請重新整理後再試。'));
if(storageMode==='sites'){api('/api/status').then(s=>{status=s;}).catch(e=>message(e.message));api('/api/session').then(s=>{session=s;renderAccount();}).catch(e=>{renderAccount();message(e.message);});}renderAccount();
window.rotaryStudio={get state(){return state;},validate,compose,buildPptx,normalizeDraft,chatGPTPrompt,normalizeImportedSlides};
if(document.modelContext?.registerTool){const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}};register({name:'get_rotary_presentation_brief',description:'取得目前簡報的主題、對象、頁數與官方來源要求，供 ChatGPT 研究並建立內容。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,openWorldHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('此工具不接受參數。');return {topic:state.title,audience:state.audience,year:state.year||'未指定',totalPages:state.pages,contentPages:state.pages-3,instructions:chatGPTPrompt()};}});register({name:'import_rotary_presentation_content',description:'把已完成且附扶輪官方來源的內容匯入目前網站，建立 15 至 20 頁簡報預覽。',inputSchema:{type:'object',properties:{slides:{type:'array',items:{type:'object',properties:{title:{type:'string'},body:{type:'string'},layout:{type:'string',enum:['text','comparison','flow']},table:{type:'string'},steps:{type:'string'},sources:{type:'array',items:{type:'object',properties:{title:{type:'string'},url:{type:'string'}},required:['title','url'],additionalProperties:false}},note:{type:'string'}},required:['title','body','layout','table','steps','sources','note'],additionalProperties:false}}},required:['slides'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},execute(input){const slides=normalizeImportedSlides(input);state.slides=[{},{},{},...slides];state.generatedAt=new Date().toISOString();state.index=3;touch();navigate(3);return {imported:true,totalPages:state.slides.length,checks:validate().map(([name,passed])=>({name,passed}))};}});register({name:'read_presentation_checks',description:'讀取目前簡報的頁數、草稿儲存狀態與匯出前檢核。不修改、不匯出。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,openWorldHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('此工具不接受參數。');return {pages:state.slides.length,step:labels[state.step],savedDraft:!!draftId,unsavedChanges:dirty,aiMode:status.aiMode,signedIn:session.signedIn,checks:validate().map(([name,passed])=>({name,passed}))};}});}
