'use strict';

const labels=['簡報設定','講稿與講師','GPT Images 生圖','圖片預覽','檢核與 PDF'];
const TOTAL_PAGES=11;
const OUTLINE_PAGES=8;
const fresh=()=>({schemaVersion:3,step:0,index:0,title:'',audience:'扶輪社友',year:'',speaker:'',role:'',bio:'',mdSource:'',mdName:'',portrait:null,portraitName:'',slides:[],reviewed:false,generatedAt:null});
const storageMode=location.hostname.endsWith('.github.io')||location.protocol==='file:'||new URLSearchParams(location.search).get('storage')==='browser'?'browser':'sites';
let state=fresh(),draftId=null,draftETag=null,dirty=false,revision=0,officialLogo=null,session={signedIn:storageMode==='browser',email:'',name:''};

const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeImage=value=>typeof value==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(value)?value:null;
function message(text){$('#notice').textContent=text;}
function touch(){dirty=true;revision++;state.reviewed=false;$('#saveStatus').textContent='有尚未儲存的修改';}
function busy(title,text=''){const overlay=$('#busyOverlay');overlay.hidden=!title;$('#busyTitle').textContent=title||'';$('#busyText').textContent=text;}
function field(key,label,type='text',placeholder=''){return `<label class="field">${label}${type==='textarea'?`<textarea data-key="${key}" placeholder="${esc(placeholder)}">${esc(state[key])}</textarea>`:`<input data-key="${key}" type="${type}" value="${esc(state[key])}" placeholder="${esc(placeholder)}">`}</label>`;}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Studio-Request':'1',...(options.headers||{})}});let result;try{result=await response.json();}catch{throw Error('網站連線未完成，請重新登入或稍後重試。');}if(!response.ok)throw Error(result.error||'操作未完成。');return result;}

function draftDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('rotary-slide-studio',1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('drafts'))db.createObjectStore('drafts',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('瀏覽器草稿儲存空間無法開啟。'));});}
async function browserDrafts(mode,id,value){const db=await draftDB();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode==='list'||mode==='get'?'readonly':'readwrite'),store=tx.objectStore('drafts'),request=mode==='list'?store.getAll():mode==='get'?store.get(id):store.put(value);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('草稿儲存未完成。'));tx.oncomplete=()=>db.close();});}

function parseOutline(text,strict=true){
  const raw=String(text||'').replace(/\r\n?/g,'\n').trim();
  const fail=error=>{if(strict)throw Error(error);return {valid:false,error,title:'',audience:'',goal:'',pages:[],sourceTitle:'',sourceURL:''};};
  if(!raw)return fail('請先上傳第一波主題大綱網站下載的 Markdown 講稿。');
  const title=(raw.match(/^#\s+(.+)$/m)?.[1]||'').trim();
  const audience=(raw.match(/^適合對象[：:]\s*(.+)$/m)?.[1]||'').trim();
  const goal=(raw.match(/^學習目標[：:]\s*(.+)$/m)?.[1]||'').trim();
  const sourceMatch=raw.match(/^參考[：:]\s*\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/m);
  const matches=[...raw.matchAll(/^##\s*第\s*(\d+)\s*頁\s*[｜|]\s*(.+)$/gm)];
  if(matches.length!==OUTLINE_PAGES)return fail(`目前辨識到 ${matches.length} 頁；講稿必須完整包含第 1 頁到第 8 頁。`);
  const pages=matches.map((match,index)=>{
    const block=raw.slice(match.index+match[0].length,matches[index+1]?.index??raw.length).trim();
    const chapterLine=block.match(/^章節[：:]\s*(.+?)(?:\s*[｜|]\s*([\d.]+)\s*分鐘)?$/m);
    const beforeNotes=block.split(/^###\s*主講者備註\s*$/m)[0];
    return {number:Number(match[1]),title:String(match[2]||'').trim(),chapter:(chapterLine?.[1]||'').trim(),minutes:Number(chapterLine?.[2]||0),points:[...beforeNotes.matchAll(/^[-*]\s+(.+)$/gm)].map(item=>item[1].trim()),visual:(block.match(/^畫面建議[：:]\s*(.+)$/m)?.[1]||'').trim(),notes:(block.match(/^###\s*主講者備註\s*\n([\s\S]*?)(?=\n##\s|$)/m)?.[1]||'').trim()};
  });
  if(!title||pages.some((page,index)=>page.number!==index+1||!page.title||!page.points.length))return fail('講稿的主題、頁碼、標題或投影片重點不完整。');
  return {valid:true,error:'',title,audience,goal,pages,sourceTitle:sourceMatch?.[1]||'',sourceURL:sourceMatch?.[2]||'',raw};
}

function promptForSlide(slide,index){
  const common='Create an original 16:9 editorial presentation background for a Rotary training deck in Taiwan. Use deep navy blue, warm gold, white, and restrained cyan accents. Professional, calm, human-centered, realistic editorial illustration or refined documentary photography. Keep the left 58 percent quiet and low-detail for typography, and keep the upper-right corner clear for an official logo that will be added later. Do not include any words, letters, numbers, logos, gear-wheel symbols, watermarks, badges, or brand marks.';
  if(slide.kind==='cover')return `${common} Cover concept: ${slide.title}. Show an uplifting scene of Rotary volunteers collaborating across generations, with cinematic depth and generous negative space.`;
  if(slide.kind==='speaker')return `${common} Speaker introduction background. Show a tasteful conference-stage atmosphere with soft architectural light, an abstract audience, and open space on the right for a real speaker portrait. Do not invent a person.`;
  if(slide.kind==='agenda')return `${common} Agenda background. Show eight connected milestones as subtle abstract forms moving from insight to action, without labels or text.`;
  return `${common} Slide ${index+1} concept: ${slide.title}. Key ideas: ${slide.points.join('; ')}. Visual direction: ${slide.visual||'one clear visual metaphor with a practical learning atmosphere'}. Avoid decorative clutter.`;
}

function buildPlan(force=false){
  const outline=parseOutline(state.mdSource);
  if(!state.speaker.trim()||!state.role.trim()||!state.bio.trim())throw Error('請先完整填寫講師姓名、職稱／扶輪社與簡介。');
  if(!state.portrait)throw Error('請先上傳已取得使用同意的講師照片。');
  if(state.slides.some(slide=>slide.background)&&!force&&!confirm('重新建立生圖任務會清除目前已上傳的 GPT Images 圖片，是否繼續？'))return false;
  state.title=state.title.trim()||outline.title;
  state.audience=state.audience.trim()||outline.audience||'扶輪社友';
  const agenda=outline.pages.map(page=>`${String(page.number).padStart(2,'0')}　${page.title}`);
  const slides=[
    {kind:'cover',title:state.title,points:[state.speaker,state.role,state.audience+(state.year?` · ${state.year}`:'')],visual:'跨世代扶輪志工合作，保留大量標題空間。'},
    {kind:'speaker',title:`講師介紹｜${state.speaker}`,points:[state.role,...state.bio.split('\n').map(line=>line.trim()).filter(Boolean).slice(0,5)],visual:'專業講師舞台氛圍，保留真實人像位置。'},
    {kind:'agenda',title:'今日分享目錄',points:agenda,visual:'八個相連里程碑，由認識走向行動。'},
    ...outline.pages.map(page=>({kind:'content',title:page.title,points:page.points.slice(0,5),visual:page.visual,notes:page.notes,chapter:page.chapter,minutes:page.minutes,sourceTitle:outline.sourceTitle,sourceURL:outline.sourceURL}))
  ];
  state.slides=slides.map((slide,index)=>({...slide,pageNumber:index+1,prompt:promptForSlide(slide,index),background:null,composed:null}));
  state.generatedAt=new Date().toISOString();state.index=0;touch();return true;
}

function masterPrompt(){
  if(state.slides.length!==TOTAL_PAGES)throw Error('請先在第 2 步建立 11 頁生圖任務。');
  return `請協助我完成「${state.title}」扶輪講師簡報的 11 張 GPT Images 背景圖。\n\n請逐頁生成 16:9 圖片。每一頁都必須遵守該頁提示詞，尤其不得生成文字、數字、Logo、齒輪標誌、水印或品牌標記。網站會使用正確文字與我提供的官方地區 Logo 完成合成。\n\n如果你正在 ChatGPT 桌面版內建瀏覽器使用本網站，請先讀取網站工具 get_rotary_image_deck_plan，依序生成圖片，再將每張結果放回對應頁面。若無法自動放回，請讓我逐張下載，再上傳至網站。\n\n${state.slides.map(slide=>`第 ${slide.pageNumber} 頁｜${slide.title}\n${slide.prompt}`).join('\n\n')}`;
}

function outlineSummary(){
  const outline=parseOutline(state.mdSource,false);
  if(!outline.valid)return state.mdSource?`<div class="outline-status warning"><b>講稿格式未通過</b><span>${esc(outline.error)}</span></div>`:'<div class="upload-empty"><b>尚未上傳 Markdown 講稿</b><span>一次只能選擇 1 個 .md 檔案。</span></div>';
  return `<div class="outline-status success"><b>${esc(state.mdName||outline.title)}｜已辨識 8 頁</b><span>${esc(outline.title)} · ${esc(outline.audience||state.audience)} · ${outline.pages.reduce((sum,page)=>sum+page.minutes,0)} 分鐘</span></div><ol class="outline-pages">${outline.pages.map(page=>`<li><b>${String(page.number).padStart(2,'0')}</b><span>${esc(page.title)}</span></li>`).join('')}</ol>`;
}

function render(){
  $('#steps').innerHTML=labels.map((label,index)=>`<button data-step="${index}" class="${index===state.step?'active':''}" aria-current="${index===state.step?'step':'false'}"><b>${index+1}</b>${label}</button>`).join('');
  $('#stepNo').textContent=`STEP 0${state.step+1} / 05`;$('#stepTitle').textContent=labels[state.step];$('#pageCount').textContent='固定 11 頁 · 圖片式簡報';$('#back').disabled=state.step===0;$('#next').hidden=state.step===4;message('');const panel=$('#panel');
  if(state.step===0)panel.innerHTML=`<div class="card"><div class="section-head"><div><p class="eyebrow">固定頁數</p><h2>每份簡報自動建立 11 頁</h2></div><span class="tag">3 頁開場＋8 頁講稿</span></div><p class="muted">頁數不需選擇。網站會依序建立封面、講師介紹、目錄，以及 Markdown 講稿中的 8 頁正式內容。</p><div class="page-formula"><b>01</b><span>封面</span><b>02</b><span>講師介紹</span><b>03</b><span>目錄</span><b>04–11</b><span>講稿內容</span></div></div><div class="card"><h2>簡報基本設定</h2>${field('title','簡報主題（上傳講稿後可自動帶入）','text','可先留白')}<div class="grid">${field('audience','分享對象')}${field('year','扶輪年度（選填）','text','例如：2027–2028')}</div></div>`;
  if(state.step===1)panel.innerHTML=`<div class="card outline-card"><div class="section-head"><div><p class="eyebrow">第一波主題大綱</p><h2>上傳單一 Markdown 講稿</h2></div><a class="button-link secondary" href="https://jimmyliao1019.github.io/rotary-first-wave-outlines/" target="_blank" rel="noopener noreferrer">開啟講稿網站</a></div><p>在來源網站選擇主題並按「下載本題講稿」，再把該份 <strong>.md</strong> 檔上傳。系統只接受 1 個檔案，並檢查是否含有完整 8 頁。</p><label class="file-drop">選擇 Markdown 講稿<input id="mdFile" type="file" accept=".md,text/markdown,text/plain"></label>${outlineSummary()}${state.mdSource?'<button id="removeMd" class="secondary">移除目前講稿</button>':''}</div><div class="card"><h2>講師基本資料</h2><div class="grid">${field('speaker','講師姓名')}${field('role','職稱／所屬扶輪社')}</div>${field('bio','講師簡介與相關經歷','textarea','每行一項，建議 3 至 5 項。')}<div class="speaker-upload"><label class="file-drop">上傳講師照片<input id="portraitFile" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="portrait-mini">${state.portrait?`<img src="${state.portrait}" alt="講師照片"><span>${esc(state.portraitName)}</span>`:'<span>請使用已取得本人同意的照片，將放入第 2 頁。</span>'}</div></div><button id="prepareDeck">結合講稿與講師資料，建立 11 頁生圖任務</button></div>`;
  if(state.step===2)panel.innerHTML=state.slides.length===TOTAL_PAGES?generationPanel():'<div class="card"><h2>尚未建立生圖任務</h2><p>請回到第 2 步，上傳完整 Markdown 講稿及講師資料。</p><button id="goInput">回到講稿與講師</button></div>';
  if(state.step===3)panel.innerHTML=state.slides.length===TOTAL_PAGES?previewPanel():'<div class="card"><h2>尚未建立圖片預覽</h2><p>請先完成講稿與生圖任務。</p></div>';
  if(state.step===4)panel.innerHTML=reviewPanel();bind();
}

function generationPanel(){const done=state.slides.filter(slide=>slide.background).length;return `<div class="card ai-card"><div class="section-head"><div><p class="eyebrow">使用自己的 ChatGPT</p><h2>逐頁使用 GPT Images 生成背景</h2></div><span class="tag ok">${done} / ${TOTAL_PAGES} 張已上傳</span></div><p>請使用 ChatGPT 的生圖能力依序製作 11 張背景圖。AI 圖不包含文字或 Logo；網站會在下一步疊加正確文字、講師照片與官方地區 Logo。</p><div class="callout">在 ChatGPT 桌面版內建瀏覽器中，可直接說：「請讀取這個網站的生圖任務，逐頁使用 GPT Images 產生圖片並放回網站。」</div><div class="actions"><button id="copyMasterPrompt">複製全部生圖任務</button><a class="button-link secondary" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">開啟 ChatGPT</a></div></div><div class="prompt-list">${state.slides.map(slide=>`<article class="prompt-row ${slide.background?'complete':''}"><div><small>第 ${slide.pageNumber} 頁 · ${slide.kind==='content'?(slide.chapter||'講稿內容'):'固定開場'}</small><h3>${esc(slide.title)}</h3><p>${esc(slide.prompt)}</p></div><div><span class="prompt-state">${slide.background?'圖片已上傳':'等待生成'}</span><button class="secondary" data-copy-prompt="${slide.pageNumber}">複製提示詞</button></div></article>`).join('')}</div>`;}
function previewCard(slide,index){return `<article class="image-slide-card ${slide.background?'complete':''}"><div class="image-slide-head"><div><small>第 ${slide.pageNumber} 頁</small><h3>${esc(slide.title)}</h3></div><span>${slide.background?'已完成':'待上傳'}</span></div><div class="image-preview">${slide.composed?`<img src="${slide.composed}" alt="第 ${slide.pageNumber} 頁合成預覽">`:`<div><b>${String(slide.pageNumber).padStart(2,'0')}</b><span>上傳本頁 GPT Images 背景後產生預覽</span></div>`}</div><div class="image-slide-actions"><label class="button-link">${slide.background?'更換圖片':'上傳圖片'}<input class="visually-hidden" data-slide-file="${index}" type="file" accept="image/png,image/jpeg,image/webp"></label><button class="secondary" data-copy-prompt="${slide.pageNumber}">複製本頁提示詞</button>${slide.background?`<button class="secondary" data-remove-image="${index}">移除</button>`:''}</div></article>`;}
function previewPanel(){const done=state.slides.filter(slide=>slide.background).length;return `<div class="card"><div class="section-head"><div><h2>逐頁上傳並檢查圖片</h2><p class="muted">每次選擇 1 張 GPT Images 圖片；網站會裁切為 16:9，再疊加正確文字、講師照片與官方 Logo。</p></div><span class="tag ${done===TOTAL_PAGES?'ok':''}">${done} / ${TOTAL_PAGES} 頁</span></div></div><div class="image-deck-grid">${state.slides.map(previewCard).join('')}</div>`;}
function checks(){const outline=parseOutline(state.mdSource,false),allImages=state.slides.length===TOTAL_PAGES&&state.slides.every(slide=>safeImage(slide.background)&&safeImage(slide.composed));return [['Markdown 講稿已完整辨識 8 頁',outline.valid],['講師姓名、職稱、簡介與照片完整',!!state.speaker.trim()&&!!state.role.trim()&&!!state.bio.trim()&&!!state.portrait],['已建立固定 11 頁簡報',state.slides.length===TOTAL_PAGES],['每一頁都有 GPT Images 背景與合成預覽',allImages],['官方地區 Logo 已載入並由網站疊加',!!officialLogo]];}
function reviewPanel(){const result=checks(),ready=result.every(item=>item[1]);return `<div class="card"><h2>輸出前檢核</h2>${result.map(item=>`<div class="status"><span>${esc(item[0])}</span><b class="${item[1]?'ok':'fail'}">${item[1]?'通過':'待完成'}</b></div>`).join('')}<label class="check"><input id="reviewed" type="checkbox" ${state.reviewed?'checked':''} ${ready?'':'disabled'}>我已逐頁檢查文字、講師照片、圖片內容及官方 Logo，並確認可輸出為 PDF。</label><button id="exportPdf" ${ready&&state.reviewed?'':'disabled'}>下載 11 頁 PDF</button><p class="help" style="margin-top:16px">PDF 每頁為 16:9 高解析度圖片，可直接播放或分享；文字已固定在圖片中，避免不同電腦產生字型與換行差異。</p></div>`;}

function bind(){
  document.querySelectorAll('[data-step]').forEach(button=>button.onclick=()=>navigate(Number(button.dataset.step)));
  document.querySelectorAll('[data-key]').forEach(input=>input.oninput=()=>{state[input.dataset.key]=input.value;touch();});
  if($('#mdFile'))$('#mdFile').onchange=uploadMarkdown;if($('#removeMd'))$('#removeMd').onclick=removeMarkdown;if($('#portraitFile'))$('#portraitFile').onchange=uploadPortrait;if($('#prepareDeck'))$('#prepareDeck').onclick=prepareDeck;if($('#goInput'))$('#goInput').onclick=()=>navigate(1);
  if($('#copyMasterPrompt'))$('#copyMasterPrompt').onclick=()=>copyText(masterPrompt(),'全部 11 頁生圖任務已複製。');
  document.querySelectorAll('[data-copy-prompt]').forEach(button=>button.onclick=()=>{const slide=state.slides[Number(button.dataset.copyPrompt)-1];copyText(slide.prompt,`第 ${slide.pageNumber} 頁提示詞已複製。`);});
  document.querySelectorAll('[data-slide-file]').forEach(input=>input.onchange=uploadSlideImage);document.querySelectorAll('[data-remove-image]').forEach(button=>button.onclick=()=>removeSlideImage(Number(button.dataset.removeImage)));
  if($('#reviewed'))$('#reviewed').onchange=event=>{state.reviewed=event.target.checked;dirty=true;revision++;$('#saveStatus').textContent='有尚未儲存的修改';$('#exportPdf').disabled=!(state.reviewed&&checks().every(item=>item[1]));};if($('#exportPdf'))$('#exportPdf').onclick=exportPdf;
}
function navigate(step){state.step=Math.max(0,Math.min(4,step));render();window.scrollTo({top:0,behavior:'smooth'});}

async function uploadMarkdown(event){const files=event.target.files;if(!files?.length)return;const file=files[0];try{if(files.length!==1||!file.name.toLowerCase().endsWith('.md'))throw Error('一次只能上傳 1 個 .md 講稿檔案。');if(file.size>2*1024*1024)throw Error('Markdown 講稿不可超過 2 MB。');const text=await file.text(),outline=parseOutline(text);if(state.slides.some(slide=>slide.background)&&!confirm('更換講稿會清除目前的生圖任務與圖片，是否繼續？'))return;state.mdSource=text;state.mdName=file.name;state.title=outline.title;state.audience=outline.audience||state.audience;state.slides=[];touch();render();message(`已讀取「${outline.title}」完整 8 頁講稿。`);}catch(error){event.target.value='';message(error.message);}}
function removeMarkdown(){if(!confirm('移除講稿會一併清除生圖任務與已上傳圖片，是否繼續？'))return;state.mdSource='';state.mdName='';state.slides=[];touch();render();message('講稿已移除。');}
async function fileToDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('檔案讀取失敗。'));reader.readAsDataURL(file);});}
async function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('無法讀取圖片。'));image.src=src;});}
async function normalizedImage(file,{width=1600,height=900,fit='cover',quality=.9}={}){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024)throw Error('請上傳 12 MB 以下的 PNG、JPG 或 WebP 圖片。');const image=await loadImage(await fileToDataURL(file));if(image.width<640||image.height<360)throw Error('圖片尺寸太小，請使用至少 640 × 360 像素的圖片。');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#eaf1fa';ctx.fillRect(0,0,width,height);const scale=fit==='contain'?Math.min(width/image.width,height/image.height):Math.max(width/image.width,height/image.height),drawWidth=image.width*scale,drawHeight=image.height*scale;ctx.drawImage(image,(width-drawWidth)/2,(height-drawHeight)/2,drawWidth,drawHeight);return canvas.toDataURL('image/jpeg',quality);}
async function uploadPortrait(event){try{const file=event.target.files?.[0];if(!file)return;state.portrait=await normalizedImage(file,{width:800,height:1000,fit:'cover',quality:.92});state.portraitName=file.name;touch();render();message('講師照片已載入。');}catch(error){event.target.value='';message(error.message);}}
function prepareDeck(){try{if(buildPlan()){state.step=2;render();window.scrollTo({top:0});message('已建立 11 頁 GPT Images 生圖任務。');}}catch(error){message(error.message);}}
async function copyText(text,success){try{await navigator.clipboard.writeText(text);message(success);}catch{message('無法複製，請允許瀏覽器存取剪貼簿。');}}
async function uploadSlideImage(event){const index=Number(event.target.dataset.slideFile),file=event.target.files?.[0];if(!file)return;try{busy(`處理第 ${index+1} 頁圖片`,'正在裁切為 16:9 並套用文字與官方 Logo。');state.slides[index].background=await normalizedImage(file);state.slides[index].composed=await composeSlide(state.slides[index],index);touch();render();message(`第 ${index+1} 頁圖片已完成合成。`);}catch(error){message(error.message);}finally{busy('');}}
function removeSlideImage(index){state.slides[index].background=null;state.slides[index].composed=null;touch();render();message(`第 ${index+1} 頁圖片已移除。`);}

function drawCover(ctx,image,x,y,width,height){const scale=Math.max(width/image.width,height/image.height),drawWidth=image.width*scale,drawHeight=image.height*scale;ctx.drawImage(image,x+(width-drawWidth)/2,y+(height-drawHeight)/2,drawWidth,drawHeight);}
function roundedRect(ctx,x,y,width,height,radius){ctx.beginPath();ctx.roundRect(x,y,width,height,radius);}
function wrappedLines(ctx,text,maxWidth,maxLines=20){const result=[];for(const paragraph of String(text||'').split('\n')){if(!paragraph){result.push('');continue;}let line='';for(const char of paragraph){const candidate=line+char;if(line&&ctx.measureText(candidate).width>maxWidth){result.push(line);line=char;}else line=candidate;}if(line)result.push(line);}return result.slice(0,maxLines);}
function drawWrapped(ctx,text,x,y,maxWidth,lineHeight,maxLines=20){const lines=wrappedLines(ctx,text,maxWidth,maxLines);lines.forEach((line,index)=>ctx.fillText(line,x,y+index*lineHeight));return y+lines.length*lineHeight;}
function drawLogo(ctx,logo){const box={x:1240,y:36,w:310,h:118};ctx.save();ctx.fillStyle='#ffffff';roundedRect(ctx,box.x,box.y,box.w,box.h,16);ctx.fill();const padding=22,ratio=logo.width/logo.height,availableW=box.w-padding*2,availableH=box.h-padding*2;let width=availableW,height=width/ratio;if(height>availableH){height=availableH;width=height*ratio;}ctx.drawImage(logo,box.x+(box.w-width)/2,box.y+(box.h-height)/2,width,height);ctx.restore();}
function drawFooter(ctx,index){ctx.font='24px "PingFang TC",sans-serif';ctx.fillStyle='#60728b';ctx.fillText(state.speaker||'扶輪講師',90,850);ctx.textAlign='right';ctx.fillText(String(index+1).padStart(2,'0'),1510,850);ctx.textAlign='left';}
async function composeSlide(slide,index){
  if(!slide.background||!officialLogo)throw Error('圖片或官方 Logo 尚未載入。');const background=await loadImage(slide.background),logo=await loadImage(officialLogo),canvas=document.createElement('canvas');canvas.width=1600;canvas.height=900;const ctx=canvas.getContext('2d');drawCover(ctx,background,0,0,1600,900);
  if(slide.kind==='cover'){const gradient=ctx.createLinearGradient(0,0,1150,0);gradient.addColorStop(0,'rgba(5,42,94,.98)');gradient.addColorStop(.68,'rgba(5,42,94,.82)');gradient.addColorStop(1,'rgba(5,42,94,.08)');ctx.fillStyle=gradient;ctx.fillRect(0,0,1250,900);ctx.fillStyle='#f7a81b';ctx.fillRect(0,872,620,28);ctx.fillStyle='#ffffff';ctx.font='700 70px "PingFang TC",sans-serif';drawWrapped(ctx,slide.title,100,310,950,92,3);ctx.font='32px "PingFang TC",sans-serif';drawWrapped(ctx,slide.points.filter(Boolean).join('　｜　'),105,650,1000,52,3);ctx.fillStyle='#dce9ff';ctx.font='25px "PingFang TC",sans-serif';ctx.fillText('國際扶輪 3510 地區',105,110);
  }else{const gradient=ctx.createLinearGradient(0,0,1080,0);gradient.addColorStop(0,'rgba(255,255,255,.99)');gradient.addColorStop(.8,'rgba(255,255,255,.94)');gradient.addColorStop(1,'rgba(255,255,255,.18)');ctx.fillStyle=gradient;ctx.fillRect(0,0,1120,900);ctx.fillStyle='#0c3c7c';ctx.fillRect(0,0,22,900);ctx.fillStyle='#0c3c7c';ctx.font='700 50px "PingFang TC",sans-serif';drawWrapped(ctx,slide.title,90,170,930,66,2);ctx.fillStyle='#f7a81b';ctx.fillRect(90,275,190,8);
    if(slide.kind==='speaker'){ctx.fillStyle='#162c49';ctx.font='30px "PingFang TC",sans-serif';let y=350;for(const point of slide.points.filter(Boolean).slice(0,6)){y=drawWrapped(ctx,`• ${point}`,110,y,760,48,2)+16;}if(state.portrait){const portrait=await loadImage(state.portrait);ctx.save();roundedRect(ctx,1110,205,360,520,28);ctx.clip();drawCover(ctx,portrait,1110,205,360,520);ctx.restore();ctx.strokeStyle='#f7a81b';ctx.lineWidth=8;roundedRect(ctx,1110,205,360,520,28);ctx.stroke();}
    }else if(slide.kind==='agenda'){ctx.fillStyle='#162c49';ctx.font='27px "PingFang TC",sans-serif';slide.points.forEach((point,i)=>{const column=i<4?0:1,row=i%4,x=110+column*500,y=350+row*95;ctx.fillStyle='#f7a81b';ctx.font='700 24px "PingFang TC",sans-serif';ctx.fillText(String(i+1).padStart(2,'0'),x,y);ctx.fillStyle='#162c49';ctx.font='27px "PingFang TC",sans-serif';drawWrapped(ctx,point.replace(/^\d+　/,''),x+55,y,390,36,2);});
    }else{ctx.fillStyle='#61728a';ctx.font='22px "PingFang TC",sans-serif';ctx.fillText(`${slide.chapter||'主題內容'}${slide.minutes?` · ${slide.minutes} 分鐘`:''}`,90,325);ctx.fillStyle='#162c49';ctx.font='30px "PingFang TC",sans-serif';let y=390;for(const point of slide.points.filter(Boolean).slice(0,5)){ctx.fillStyle='#f7a81b';ctx.beginPath();ctx.arc(113,y-10,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#162c49';y=drawWrapped(ctx,point,140,y,780,45,3)+18;}if(slide.sourceURL){ctx.fillStyle='#61728a';ctx.font='18px sans-serif';drawWrapped(ctx,`參考：${slide.sourceTitle||slide.sourceURL}`,90,805,900,26,1);}}drawFooter(ctx,index);
  }
  drawLogo(ctx,logo);return canvas.toDataURL('image/jpeg',.92);
}

async function setSlideBackground(pageNumber,dataURL){const index=Number(pageNumber)-1;if(index<0||index>=TOTAL_PAGES)throw Error('頁碼必須介於 1 至 11。');const image=safeImage(dataURL);if(!image||image.length>12*1024*1024)throw Error('圖片必須是 12 MB 以下的 PNG、JPG 或 WebP data URL。');state.slides[index].background=image;state.slides[index].composed=await composeSlide(state.slides[index],index);touch();if(state.step===3)render();return {pageNumber,ready:true,completed:state.slides.filter(slide=>slide.background).length,total:TOTAL_PAGES};}
async function refreshComposites(){for(let i=0;i<state.slides.length;i++)if(state.slides[i].background)state.slides[i].composed=await composeSlide(state.slides[i],i);}
function snapshot(){return {...state,pages:TOTAL_PAGES,slides:state.slides.map(({composed,...slide})=>slide)};}
async function saveDraft(copy=false){if(storageMode==='sites'&&!session.signedIn){location.href='/signin-with-chatgpt?return_to=%2F';return;}const data=snapshot(),startRevision=revision,id=copy?null:draftId;$('#saveDraft').disabled=true;$('#saveStatus').textContent='正在儲存…';try{let result;if(storageMode==='browser'){const updatedAt=new Date().toISOString(),localId=id||crypto.randomUUID();await browserDrafts('put',localId,{id:localId,updatedAt,title:state.title||'未命名簡報',speaker:state.speaker,pages:TOTAL_PAGES,data});result={id:localId,etag:updatedAt,updatedAt};}else result=await api(id?`/api/drafts/${id}`:'/api/drafts',{method:id?'PUT':'POST',headers:id?{'If-Match':draftETag}:{},body:JSON.stringify(data)});draftId=result.id;draftETag=result.etag;if(revision===startRevision)dirty=false;$('#saveStatus').textContent=dirty?'已儲存，仍有較新的修改':`已儲存 ${new Date(result.updatedAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`;message('草稿已儲存，包含講稿、講師資料及已上傳圖片。');if($('#draftDialog').open)await listDrafts();}catch(error){$('#saveStatus').textContent='儲存未完成';message(error.message);}finally{$('#saveDraft').disabled=storageMode==='sites'&&!session.signedIn;}}
async function listDrafts(){const list=$('#draftList');list.innerHTML='<p>正在讀取草稿…</p>';try{const result=storageMode==='browser'?{drafts:(await browserDrafts('list')).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}:await api('/api/drafts');list.innerHTML=result.drafts.length?result.drafts.map(draft=>`<div class="draft-row"><div><strong>${esc(draft.title)}</strong><p class="help">${esc(draft.speaker||'尚未填寫講師')} · ${esc(draft.pages||TOTAL_PAGES)} 頁 · ${esc(new Date(draft.updatedAt).toLocaleString('zh-TW'))}</p></div><button data-open="${esc(draft.id)}">開啟</button></div>`).join(''):'<div class="card"><p>尚無草稿。</p></div>';document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>openDraft(button.dataset.open));}catch(error){list.textContent=error.message;}}
function normalizeDraft(data){if(!data||![2,3].includes(data.schemaVersion))throw Error('草稿版本不正確。');const next={...fresh(),...data,schemaVersion:3,mdSource:String(data.mdSource||data.outlineSource||''),mdName:String(data.mdName||''),portrait:safeImage(data.portrait),slides:Array.isArray(data.slides)&&data.schemaVersion===3?data.slides.slice(0,TOTAL_PAGES).map(slide=>({...slide,background:safeImage(slide.background),composed:null})):[]};for(const key of ['title','audience','year','speaker','role','bio'])next[key]=String(next[key]||'');next.step=0;next.index=0;next.reviewed=false;return next;}
async function openDraft(id){if(dirty&&!confirm('目前有尚未儲存的修改。開啟其他草稿將放棄這些修改，是否繼續？'))return;try{busy('開啟草稿','正在重新建立圖片預覽。');const result=storageMode==='browser'?await browserDrafts('get',id):await api(`/api/drafts/${id}`);if(!result)throw Error('找不到這份草稿。');state=normalizeDraft(result.data);draftId=result.id;draftETag=result.etag||result.updatedAt;await refreshComposites();dirty=false;revision++;$('#saveStatus').textContent=`已開啟：${state.title||'未命名簡報'}`;$('#draftDialog').close();render();message('草稿已重新開啟。');}catch(error){$('#draftList').textContent=error.message;}finally{busy('');}}
async function exportPdf(){if(!state.reviewed||!checks().every(item=>item[1]))return;try{busy('製作 PDF','正在把 11 張合成圖寫入 PDF。');await refreshComposites();const blob=RotaryPDF.buildJpegPdf(state.slides.map(slide=>({dataURL:slide.composed,width:1600,height:900})));const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${(state.title||'扶輪簡報').replace(/[\\/:*?"<>|]/g,'_')}.pdf`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);message('PDF 已產生，請查看瀏覽器下載項目。');}catch(error){message(`PDF 匯出未完成：${error.message}`);}finally{busy('');}}

function renderAccount(){const label=$('#accountStatus'),action=$('#accountAction');if(storageMode==='browser'){label.textContent='草稿儲存在此瀏覽器';action.hidden=true;action.style.display='none';$('#draftStorageHelp').textContent='草稿只儲存在這台裝置的瀏覽器，可重新開啟繼續編輯。';}else{label.textContent=session.signedIn?`已登入：${session.name||session.email||'ChatGPT 使用者'}`:'尚未登入';action.hidden=false;action.style.display='';action.textContent=session.signedIn?'登出':'使用 ChatGPT 登入';action.href=session.signedIn?'/signout-with-chatgpt?return_to=%2F':'/signin-with-chatgpt?return_to=%2F';}$('#saveDraft').disabled=storageMode==='sites'&&!session.signedIn;$('#openDrafts').disabled=storageMode==='sites'&&!session.signedIn;}
$('#back').onclick=()=>navigate(state.step-1);$('#next').onclick=()=>navigate(state.step+1);$('#saveDraft').onclick=()=>saveDraft();$('#openDrafts').onclick=()=>{if(storageMode==='sites'&&!session.signedIn){location.href='/signin-with-chatgpt?return_to=%2F';return;}$('#draftDialog').showModal();listDrafts();};$('#closeDrafts').onclick=()=>$('#draftDialog').close();$('#saveCopy').onclick=()=>saveDraft(true);$('#newDraft').onclick=()=>{if(dirty&&!confirm('放棄尚未儲存的修改，建立新簡報？'))return;state=fresh();draftId=null;draftETag=null;dirty=false;revision++;$('#saveStatus').textContent='新簡報';$('#draftDialog').close();render();};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
render();fetch('assets/district-logo.png').then(response=>{if(!response.ok)throw Error('Logo 載入失敗');return response.blob();}).then(blob=>fileToDataURL(blob)).then(data=>{officialLogo=data;}).catch(()=>message('官方 Logo 未能載入，請重新整理後再試。'));if(storageMode==='sites')api('/api/session').then(value=>{session=value;renderAccount();}).catch(error=>{renderAccount();message(error.message);});renderAccount();
window.rotaryStudio={get state(){return state;},parseOutline,buildPlan,masterPrompt,composeSlide,setSlideBackground,checks};
if(document.modelContext?.registerTool){const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}};register({name:'get_rotary_image_deck_plan',description:'讀取已上傳的 8 頁 Markdown 講稿、講師資料與 11 頁 GPT Images 生圖提示詞。不修改網頁。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,openWorldHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('此工具不接受參數。');const outline=parseOutline(state.mdSource);if(state.slides.length!==TOTAL_PAGES)buildPlan();return {title:state.title,audience:state.audience,year:state.year||'未指定',speaker:{name:state.speaker,role:state.role,bio:state.bio},outlinePages:outline.pages,totalPages:TOTAL_PAGES,slides:state.slides.map(({pageNumber,title,kind,prompt,background})=>({pageNumber,title,kind,prompt,imageReady:!!background})),instructions:'逐頁使用 GPT Images 生成 16:9 背景，不得含文字、Logo、齒輪符號或水印。網站會疊加正確文字與官方 Logo。'};}});register({name:'import_rotary_slide_background',description:'將一張已由 GPT Images 生成的背景圖放入指定簡報頁，並由網站疊加正確文字與官方地區 Logo。',inputSchema:{type:'object',properties:{pageNumber:{type:'integer',minimum:1,maximum:11},imageDataUrl:{type:'string',description:'PNG、JPEG 或 WebP 的 base64 data URL。'}},required:['pageNumber','imageDataUrl'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},execute:async input=>setSlideBackground(input.pageNumber,input.imageDataUrl)});register({name:'read_rotary_image_deck_checks',description:'檢查 Markdown、講師資料、11 頁圖片與 PDF 匯出準備狀態。不修改網頁。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,openWorldHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('此工具不接受參數。');return {completedImages:state.slides.filter(slide=>slide.background).length,totalPages:TOTAL_PAGES,checks:checks().map(([name,passed])=>({name,passed}))};}});}
