'use strict';
(()=>{
const ascii=value=>new TextEncoder().encode(value);
const concat=parts=>{const length=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(length);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;};
function jpegBytes(dataURL){const match=String(dataURL||'').match(/^data:image\/jpeg;base64,([A-Za-z0-9+/=]+)$/);if(!match)throw Error('PDF 僅接受網站完成合成的 JPEG 頁面。');const binary=atob(match[1]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function objectBytes(number,body){return concat([ascii(`${number} 0 obj\n`),typeof body==='string'?ascii(body):body,ascii('\nendobj\n')]);}
function streamObject(number,dictionary,stream){return objectBytes(number,concat([ascii(`<< ${dictionary} /Length ${stream.length} >>\nstream\n`),stream,ascii('\nendstream')]));}
function buildJpegPdf(pages,{width=960,height=540}={}){if(!Array.isArray(pages)||!pages.length)throw Error('沒有可輸出的簡報頁面。');const objects=[],kids=[];objects[1]=objectBytes(1,'<< /Type /Catalog /Pages 2 0 R >>');for(let i=0;i<pages.length;i++){const pageNo=3+i*3,imageNo=pageNo+1,contentNo=pageNo+2,page=pages[i],image=jpegBytes(page.dataURL);kids.push(`${pageNo} 0 R`);objects[pageNo]=objectBytes(pageNo,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /XObject << /Im0 ${imageNo} 0 R >> >> /Contents ${contentNo} 0 R >>`);objects[imageNo]=streamObject(imageNo,`/Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode`,image);const drawing=ascii(`q\n${width} 0 0 ${height} 0 0 cm\n/Im0 Do\nQ`);objects[contentNo]=streamObject(contentNo,'',drawing);}objects[2]=objectBytes(2,`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`);const header=concat([ascii('%PDF-1.4\n%'),new Uint8Array([255,255,255,255]),ascii('\n')]),parts=[header],offsets=[0];let offset=header.length;for(let i=1;i<objects.length;i++){offsets[i]=offset;parts.push(objects[i]);offset+=objects[i].length;}const xrefOffset=offset,xref=[`xref\n0 ${objects.length}\n`,`0000000000 65535 f \n`];for(let i=1;i<objects.length;i++)xref.push(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);parts.push(ascii(xref.join('')));parts.push(ascii(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`));return new Blob(parts,{type:'application/pdf'});}
globalThis.RotaryPDF={buildJpegPdf};
})();
