'use strict';
function buildPptx(st,Constructor){const p=new Constructor();p.layout='LAYOUT_WIDE';p.author=st.speaker;p.subject='國際扶輪 3510 地區';p.title=st.title;p.lang='zh-TW';p.theme={headFontFace:'思源黑體 TW',bodyFontFace:'思源黑體 TW',lang:'zh-TW'};const ink='162C49',blue='17458F',gold='F7A81B';
const rect=(s,x,y,w,h,color)=>s.addShape(p.ShapeType.rect,{x,y,w,h,fill:{color},line:{transparency:100}});
const text=(s,value,x,y,w,h,size=22,color=ink,bold=false)=>s.addText(value,{x,y,w,h,fontFace:'思源黑體 TW',fontSize:size,color,bold,margin:0,fit:'shrink',breakLine:false,paraSpaceAfter:8,valign:'top'});
const contain=(data,x,y,w,h)=>{const bytes=Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0));const view=new DataView(bytes.buffer);let iw=1,ih=1;if(bytes[0]===137&&bytes[1]===80){iw=view.getUint32(16);ih=view.getUint32(20);}else if(bytes[0]===255&&bytes[1]===216){let i=2;while(i+9<bytes.length){if(bytes[i]!==255){i++;continue;}const marker=bytes[i+1],len=view.getUint16(i+2);if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){ih=view.getUint16(i+5);iw=view.getUint16(i+7);break;}if(!len)break;i+=len+2;}}const scale=Math.min(w/iw,h/ih);return {x:x+(w-iw*scale)/2,y:y+(h-ih*scale)/2,w:iw*scale,h:ih*scale};};
st.slides.forEach((s,i)=>{const slide=p.addSlide(),cover=s.kind==='cover',layout=s.layout||'text';slide.background={color:cover?blue:'FFFFFF'};rect(slide,0,0,.14,7.5,cover?gold:blue);text(slide,'國際扶輪 3510 地區',.75,.48,7,.3,12,cover?'DCE9FF':blue);
if(st.logo){const w=2.0,h=w/st.logoRatio;rect(slide,9.75,.2,2.95,1.48,'FFFFFF');slide.addImage({data:st.logo,x:10.225,y:.56,w,h});}
text(slide,s.title,.75,cover?2.35:1.8,11.5,1.05,cover?34:28,cover?'FFFFFF':ink,true);
if(s.kind==='speaker'&&st.portrait){slide.addImage({data:st.portrait,x:8.6,y:2.2,w:3.36,h:4.2});text(slide,s.body,.75,3.2,7,3.1,22);}
else if(layout==='image'){text(slide,s.body,.75,3.2,5.5,3.05,22);if(s.image)slide.addImage({data:s.image,...contain(s.image,6.8,3.05,5.7,3.12)});text(slide,s.imageCaption||'',6.8,6.23,5.7,.3,11,'61728A');}
else if(layout==='comparison'){text(slide,s.body,.75,2.92,11.5,.68,17);const rows=String(s.table||'').split('\n').filter(x=>x.trim()).map(line=>line.split('|').map(x=>x.trim()));if(rows.length)slide.addTable(rows.map((r,ri)=>r.map(t=>({text:t,options:ri===0?{bold:true,fill:'EAF1FA',color:blue}:{}}))),{x:.75,y:3.8,w:11.6,h:2.4,colW:11.6/rows[0].length,rowH:.48,fontFace:'思源黑體 TW',fontSize:17,color:ink,border:{type:'solid',color:'DCE4EE',pt:1},margin:8,fill:'F4F7FB',bold:false,autoPage:false,verbose:false}); // cells remain native and editable
}
else if(layout==='flow'){text(slide,s.body,.75,2.95,11.6,.8,18);const steps=String(s.steps||'').split('\n').map(x=>x.trim()).filter(Boolean),n=steps.length,gap=.35,w=(11.55-gap*(n-1))/n;steps.forEach((label,k)=>{const x=.75+k*(w+gap);rect(slide,x,4,w,1.8,'EAF1FA');rect(slide,x,4,w,.12,gold);text(slide,String(k+1).padStart(2,'0'),x+.16,4.3,w-.32,.36,18,blue,true);text(slide,label,x+.16,4.85,w-.32,.78,n>4?16:19,ink);if(k<n-1)slide.addShape(p.ShapeType.chevron,{x:x+w+.08,y:4.72,w:.19,h:.3,fill:{color:blue},line:{transparency:100}});});}
else if(s.kind==='agenda'){const lines=s.body.split('\n'),cut=Math.ceil(lines.length/2);[lines.slice(0,cut),lines.slice(cut)].forEach((ls,j)=>text(slide,ls.join('\n'),.75+j*5.95,3.05,5.5,3.55,16));}
else text(slide,s.body,.75,cover?4.85:3.25,11.4,cover?1.25:3.05,cover?19:22,cover?'FFFFFF':ink);
const refs=(s.sources||[]).filter(r=>/^https?:\/\//.test(r.url));if(refs.length){const runs=refs.map((r,k)=>({text:`[${k+1}] ${r.title.slice(0,24)}　`,options:{hyperlink:{url:r.url},color:'005DAA',underline:true}}));slide.addText(runs,{x:.75,y:6.55,w:11.5,h:.25,fontFace:'思源黑體 TW',fontSize:9,margin:0,fit:'shrink'});}
text(slide,`${st.speaker}　／　${String(i+1).padStart(2,'0')}`,.75,6.95,10,.22,10,cover?'DCE9FF':'61728A');slide.addNotes(['品牌依據：使用者提供的扶輪標誌使用規範，2019 年 12 月版。Logo 採指定地區Logo.png，原比例保留。',...refs.map((r,k)=>`來源 [${k+1}] ${r.title}\n${r.url}\n查詢日期：${r.fetchedAt||'使用者提供'}`),s.note||''].join('\n\n'));});return p;}
if(typeof module!=='undefined')module.exports={buildPptx};
